version: "3.9"
services:
  cloudbeaver:
    container_name: dbeaver
    image: dbeaver/cloudbeaver:latest # Or a specific version like 23.2
    restart: unless-stopped
    ports:
      - "8978:8978" # Host_port:Container_port
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace # Persist workspace data
volumes:
  cloudbeaver_data:
    driver: local
